name = Plot
description = Plot page layout
template = plot-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/plot/plot.layout.css
stylesheets[all][] = css/layouts/plot/plot.layout.no-query.css