name = Video holder
description = A single sidebar interior page
template = videoHolder-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/videoHolder/videoHolder.layout.css
stylesheets[all][] = css/layouts/videoHolder/videoHolder.layout.no-query.css