name = Image holder
description = The Image holder layout
template = imageHolder-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/imageHolder/imageHolder.layout.css
stylesheets[all][] = css/layouts/imageHolder/imageHolder.layout.no-query.css