name = Video
description = The Video landing page layout
template = video-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[box] = Intro
regions[box] = Box
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/video/video.layout.css
stylesheets[all][] = css/layouts/video/video.layout.no-query.css