name = Tracking
description = The Tracking page layout
template = tracking-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[box] = Intro
regions[box] = Box
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/tracking/tracking.layout.css
stylesheets[all][] = css/layouts/tracking/tracking.layout.no-query.css