name = Image Gallery
description = The Image Gallery landing page layout
template = imageGallery-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[box] = Intro
regions[box] = Box
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/imageGallery/imageGallery.layout.css
stylesheets[all][] = css/layouts/imageGallery/imageGallery.layout.no-query.css